/**
 * The Forgotten Server - a free and open-source MMORPG server emulator
 * Copyright (C) 2019  Mark Samman <mark.samman@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include "server/netWork/protocol/protocolgame/clientpackets/accepttrade.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/addbudy.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/answermodaldialog.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/applyclearingcharm.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/applyimbuement.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/attack.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/browsefield.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/bugreport.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/buyingameshopoffer.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/buyobject.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/cancel.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/clearimbuingdialog.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/closecontainer.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/closedepotsearch.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/closenpcchannel.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/depotsearchretrieve.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/depotsearchtype.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/editbuddy.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/editlist.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/edittext.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/equipobject.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/excludefromchannel.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/extendedopcode.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/follow.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/getchannels.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/getoutfit.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/getquestline.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/getquestlog.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/goeast.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/gonorth.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/gonortheast.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/gonorthwest.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/gopath.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/gosouth.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/gosoutheast.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/gosouthwest.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/gowest.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/greet.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/highscores.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/inspectobject.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/invitetochannel.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/invitetoparty.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/joinchannel.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/joinparty.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/leavechannel.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/leaveparty.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/look.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/lookatcreature.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/looknpctrade.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/looktrade.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/lootcontainer.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/marketaccept.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/marketbrowse.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/marketcancel.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/marketcreate.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/marketleave.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/monsterbonuseffectaction.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/mount.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/moveobject.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/openchannel.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/opencyclopediacharacterinfo.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/opendepotsearch.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/openingameshop.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/openmonstercyclopediamonsters.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/openmonstercyclopediarace.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/openparentcontainer.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/partyhuntanalyzer.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/passleadership.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/ping.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/pingback.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/preyaction.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/preyhuntingtaskaction.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/privatechannel.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/quickloot.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/quicklootblackwhitelist.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/quitgame.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/rejecttrade.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/removebuddy.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/requestshopoffers.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/revokeinvitation.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/rotateeast.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/rotatenorth.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/rotatesouth.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/rotatewest.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/seekincontainer.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/sellobject.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/setoutfit.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/settatics.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/shareexperience.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/showoffsocket.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/stashaction.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/stop.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/talk.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/teamfinderassembleteam.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/teamfinderjointeam.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/teleport.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/togglewrapstate.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/trackbestiaryrace.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/tradeobject.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/transfercurrency.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/turnobject.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/upcontainer.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/useobject.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/useoncreature.hpp"
#include "server/netWork/protocol/protocolgame/clientpackets/usetwoobjects.hpp"
